name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.x

      - name: Install vsce
        run: |
          npm install -g @vscode/vsce
          vsce -V

      - name: Package
        run: |
          vsce package

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 3body-vscode-language-server-extension
          path: |
            3body-vscode-language-server*.vsix